### ISSUE TITLE
[Bug] Wdired does not work with expanded subtrees

### ISSUE THREAD

**Issue by gcv** [alexluigit/dirvish#94] opened 2022-07-21 04:43 UTC
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [FAQ|CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [ ] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

Editing file names using wdired in a situation where the changed file name is inside an expanded subtree does not work.

### Steps to reproduce

Make a sample test directory structure with at least one level. Point dirvish at this directory structure. Expand it. Turn on wdired and edit a file name in child subdirectory. It will fail to persist.

### Expected behavior

Wdired should work in subtrees.

### OS

MacOS

### Emacs Version

27

**Comment by alexluigit** [comment] 2022-07-21 16:53
I'm not able to reproduce this on Emacs 29, I'll try to repro this on 27 after I find the way to install it.

**Comment by gcv** [comment] 2022-07-22 05:32
The problem still seems to happen with Emacs 28. dired-subtree has the same problem, so it might be tricky to deal with. If it's fixed for version 29 because of changes to Emacs itself, then maybe it's best to let it go at the Dirvish level.

**Comment by alexluigit** [comment] 2022-07-22 11:01
> If it's fixed for version 29 because of changes to Emacs itself, then maybe it's best to let it go at the Dirvish level.

I agree, so closing for now.  If anyone experience the same issue on Emacs 29 we can reopen it then.

**Closed by alexluigit** 2022-07-22 11:01 UTC
Labels: bug, good first issue
