### ISSUE TITLE
[Bug] Weird Behavior of 'dirvish-quit'

### ISSUE THREAD

**Issue by overideal** [alexluigit/dirvish#148] opened 2022-09-20 08:26 UTC
### Thank you for the bug report

- [X] I am using the latest version of `dirvish` related packages.
- [X] I checked [CUSTOMIZING|EXTENSIONS](https://github.com/alexluigit/dirvish#resources).
- [X] You may also try reproduce the issue using clean environment and minimal configurations with
the command `emacs -Q`.

### Bug description

`dirvish-quit` might be bugged, see below.

### Steps to reproduce

With emacs -Q, run
```
(require 'dirvish)
(dirvish-override-dired-mode)
```
Press C-x C-j (`dired-jump`) and then C-x C-f and open e.g. the .emacs.d directory in Dirvish.
Then press q in the .emacs.d buffer. This will kill the other (!) Dirvish buffer and bury the .emacs.d buffer.

### Expected behavior

Kill or bury the currently selected Dirvish buffer.
In fact, I think the `dirvish-quit` command might need some better documentation. Does Dirvish group the directories in different sessions? When does it kill and when does it bury the buffer?

### OS

Linux

### Emacs Version

29

**Comment by aikrahguzar** [comment] 2022-09-20 13:16
This is controlled by `dirvish-reuse-session`. If you set it to `nil`, `dirvish-quit` will behave as you expect. But then `dired-jump` will create a new buffer every time you invoke it.

**Comment by alexluigit** [comment] 2022-09-20 15:29
Added some docs for it in 33da58759d1895dbdb406af2671f55721af881d1. I'm closing it since it is not a bug. If you have any ideas please feel free to join [this discussion](https://github.com/alexluigit/dirvish/discussions/102).

**Closed by alexluigit** 2022-09-20 15:29 UTC
Labels: bug
